version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}   
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}  
    PYTHONPATH: /opt/airflow
  volumes:
    - ../dags:/opt/airflow/dags
    - ../pipelines:/opt/airflow/pipelines
    - ../dags/utils.py:/opt/airflow/utils.py
  depends_on:
      postgres:
        condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:                                    # ← agregar
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 10s

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create \
        --username admin \
        --password admin \
        --firstname Luis \
        --lastname Ramon \
        --role Admin \
        --email admin@email.com
      "
    logging:
      driver: awslogs 
      options:
        awslogs-group: /latam-turismo/airflow
        awslogs-region: us-east-1
        awslogs-stream: init

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    command: webserver
    logging:
      driver: awslogs
      options:
        awslogs-group: /latam-turismo/airflow
        awslogs-region: us-east-1
        awslogs-stream: webserver

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    logging:
      driver: awslogs
      options:
        awslogs-group: /latam-turismo/airflow
        awslogs-region: us-east-1
        awslogs-stream: scheduler

volumes:
  postgres_db: